name: 'quality'
on: 'push'
jobs:
  check-lint:
    name: check-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.18.3
      - run: npm ci
      - run: npm run lint
